/* This file is auto-generated by SST. Do not edit. */
/* tslint:disable */
/* eslint-disable */
/* deno-fmt-ignore-file */

declare module "sst" {
  export interface Resource {
    "CLOUDFLARE_API_TOKEN": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "CLOUDFLARE_DEFAULT_ACCOUNT_ID": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "CLOUDFLARE_R2_ACCESS_KEY_ID": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "CLOUDFLARE_R2_SECRET_ACCESS_KEY": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "PrivateStorage": {
      "name": string
      "type": "sst.cloudflare.Bucket"
    }
    "PublicStorage": {
      "name": string
      "type": "sst.cloudflare.Bucket"
    }
    "Remotion": {
      "bucketName": string
      "bucketUrl": string
      "functionName": string
      "siteUrl": string
      "type": "sst.sst.Linkable"
    }
    "RemotionBucket": {
      "name": string
      "type": "sst.cloudflare.Bucket"
    }
    "RemotionSite": {
      "type": "sst.cloudflare.StaticSite"
      "url": string
    }
    "Web": {
      "type": "sst.cloudflare.SolidStart"
      "url": string
    }
  }
}
/// <reference path="sst-env.d.ts" />

import "sst"
export {}