// prettier-ignore

export const secret = {
  CLOUDFLARE_API_TOKEN: new sst.Secret('CLOUDFLARE_API_TOKEN', process.env.CLOUDFLARE_API_TOKEN),
  CLOUDFLARE_DEFAULT_ACCOUNT_ID: new sst.Secret('CLOUDFLARE_DEFAULT_ACCOUNT_ID', sst.cloudflare.DEFAULT_ACCOUNT_ID),
  CLOUDFLARE_R2_ACCESS_KEY_ID: new sst.Secret('CLOUDFLARE_R2_ACCESS_KEY_ID', process.env.CLOUDFLARE_R2_ACCESS_KEY_ID),
  CLOUDFLARE_R2_SECRET_ACCESS_KEY: new sst.Secret('CLOUDFLARE_R2_SECRET_ACCESS_KEY', process.env.CLOUDFLARE_R2_SECRET_ACCESS_KEY),
  DATABASE_USERNAME: new sst.Secret('DATABASE_USERNAME', process.env.DATABASE_USERNAME),
  DATABASE_PASSWORD: new sst.Secret('DATABASE_PASSWORD', process.env.DATABASE_PASSWORD),
}
export const allSecrets = Object.values(secret)
